version: "3"

services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    links:
      - mariadb:mariadb

  mariadb:
    image: mariadb:10.1.21
    ports:
      - "13306:3306"
    environment:
      - MYSQL_DATABASE=laravel_app
      - MYSQL_ROOT_PASSWORD=password
